### ISSUE TITLE
module 'google.generativeai' has no attribute 'GenerativeModel' 

### ISSUE THREAD

**Issue by kegbo** [google/generative-ai-python#118]
### Description of the bug:

Executing this code
with either
`from langchain_google_genai import ChatGoogleGenerativeAI`

or

`from langchain_google_genai.chat_models import ChatGoogleGenerativeAI`

```
def generate_lecture(topic:str, context:str):
    
  template ="""
  As an accomplished university professor and expert in {topic}, your task is to develop an elaborate, exhaustive, and highly detailed lecture on the subject. 
  Remember to generate content ensuring both novice learners and advanced students can benefit from your expertise.
  while leveraging the provided context
  
  Context: {context} """

  
  prompt = ChatPromptTemplate.from_template(template)

  model = ChatGoogleGenerativeAI(model="gemini-pro", google_api_key=palm_api_key)

 
  response = model.invoke(template)
  return response.content
```

### Actual vs expected behavior:

**_Actual behaviour_**
The error below is thrown
```
  File "C:\Users\ibokk\RobotForge\mvp\service\llm.py", line 80, in generate_lecture
    model = ChatGoogleGenerativeAI(model="gemini-pro", google_api_key=palm_api_key)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ibokk\anaconda3\envs\robotforge\Lib\site-packages\langchain_core\load\serializable.py", line 97, in __init__
    super().__init__(**kwargs)
  File "pydantic\main.py", line 339, in pydantic.main.BaseModel.__init__
  File "pydantic\main.py", line 1102, in pydantic.main.validate_model
  File "C:\Users\ibokk\anaconda3\envs\robotforge\Lib\site-packages\langchain_google_genai\chat_models.py", line 502, in validate_environment
    values["_generative_model"] = genai.GenerativeModel(model_name=model)
                                  ^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'google.generativeai' has no attribute 'GenerativeModel
```

**_Expected behaviour_**

A poor result will be random text generated which is not relevant to the prompt provided. An excellent result will be text generated relevant to the template provided.

### Any other information you'd like to share?

OS: Windows 11
Env: Conda 23.7.2, python: 3.11
Package: google-gen-ai : 0.3.1

**Comment by haseeb-heaven** [comment]
Try using this command `pip install google-generativeai==0.3.1` i had this error but its not fixed and i am running on MacOS.

Python  version:
```Python 3.11.1```
Here are details:
```c++
Name: google-generativeai
Version: 0.3.1
Summary: Google Generative AI High level API client library and tools.
Home-page: https://github.com/google/generative-ai-python
Author: Google LLC
Author-email: googleapis-packages@google.com
License: Apache 2.0
Location: /Users/haseeb-mir/Library/Python/3.11/lib/python/site-packages
Requires: google-ai-generativelanguage, google-api-core, google-auth, protobuf, tqdm
Required-by: langchain-google-genai
```

**Comment by Controls-Cat5e** [comment]
Anything above 3.10 works for me on python venv, especially on streamlit cloud servers. This looks like a python version issue/ runtime issues.

**Comment by Andy963** [comment]
if the env is < 3.9, when you run `pip install google-generativeai` you will install a package like: 0.1.0rc1, and when you run :
```
model = genai.GenerativeModel(model_name="gemini-pro", generation_config=generation_config, safety_settings=safety_settings)
```
will raise : "AttributeError: module 'google.generativeai' has no attribute 'GenerativeModel'"

**Comment by haseeb-heaven** [comment]
> if the env is < 3.9, when you run `pip install google-generativeai` you will install a package like: 0.1.0rc1, and when you run :
> 
> ```
> model = genai.GenerativeModel(model_name="gemini-pro", generation_config=generation_config, safety_settings=safety_settings)
> ```
> 
> will raise : "AttributeError: module 'google.generativeai' has no attribute 'GenerativeModel'"

Its solved you need Python 3.10 to work close this issue now.

**Comment by jalajc** [comment]
Was working fine until today morning...
getting the same error now... using it in Google Colab
Python: 3.10.12.

is something changed?

**Comment by jalajc** [comment]
> Was working fine until today morning... getting the same error now... using it in Google Colab Python: 3.10.12.
> 
> is something changed?

just checked, smoothing doubtful I found in install, this is default behaviour on colab when I do `pip install google-generativeai`
```
Requirement already satisfied: google-generativeai in /usr/local/lib/python3.10/dist-packages (0.2.2)
Requirement already satisfied: google-ai-generativelanguage==0.3.3 in /usr/local/lib/python3.10/dist-packages (from google-generativeai) (0.3.3)
Requirement already satisfied: google-auth in /usr/local/lib/python3.10/dist-packages (from google-generativeai) (2.17.3)
Requirement already satisfied: google-api-core in /usr/local/lib/python3.10/dist-packages (from google-generativeai) (2.11.1)
```

**Comment by bezir** [comment]
Switch to python 3.10 kernel

then
`pip install --upgrade pip`
`pip install google-generativeai --upgrade`

**Comment by BwL1289** [comment]
Why was this closed? Downgrading to 3.10 is not a solution. Is there a workaround for 3.12?

**Comment by shuantsu** [comment]
working for me with python 3.12.3 on windows 11 but not working on python 3.12.3 or python 3.10.6 on android with kotlin+chaquopy....
